services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080" # Adjust the ports if necessary
    command: ["./target/release/rust-news-topic-aggregator"]